# Запускаем сборку на Windows Server 2022
image: Visual Studio 2022

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  # Запускаем SUT в фоновом режиме, НЕ БЛОКИРУЯ скрипт (флаг /B)
  - start /B java -jar ./artifacts/app-mbank.jar
  # Ждем 10 секунд, чтобы приложение успело запуститься
  - ps: Start-Sleep -s 10

build_script:
  # Запускаем тесты с помощью Windows-скрипта gradlew.bat
  - gradlew.bat test --info