image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main
build: off

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-mbank.jar &
  - sleep 15

build_script:
  - ./gradlew test --info