name: Java CI with Gradle
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: { java-version: '11', distribution: 'temurin' }
      - run: chmod +x gradlew
      - run: java -jar ./artifacts/app-month.jar &
      - run: sleep 10
      - run: ./gradlew test --info